### ISSUE TITLE
[Bug] Weird white layer in Home screen when the application is in Light Mode

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#17]
## Issue

The application is showing a weird white layer when the phone's setting is in Light Mode. This causes the content on Home screen is difficult to see.

<img src="https://user-images.githubusercontent.com/70877098/175494039-d02e94d6-e1e0-4f2b-af9b-597c081b57cb.jpeg" width="300">

## Expect

The contents on Home screen must be clearly visible regardless of the phone's appearance mode settings like design.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/175494428-73fd33c7-709e-4c27-b38c-34409406939f.mp4

**Comment by nkhanh44** [comment]
That's my fault for not testing app from iOS 15.+, because there is some change on `UICollectionView` 's default color for iOS above 15.0 😿 . I just installed the newest macOS + Xcode to test on iOS 15.+ and fixed and explained it in this below PR. ❤️ 
ref: https://github.com/nkhanh44/Survey_Nimble/pull/21
