### ISSUE TITLE
[Bug] Unable to swipe occasionally through the survey items in Home screen

### ISSUE THREAD

**Issue by minhnimble** [nkhanh44/Survey_Nimble#20]
## Issue

When swiping through the survey items in Home screen, there is sometimes an in-between swipe that doesn't work and the users are unable to swipe smoothly through the items. This causes an intermittent feeling when scrolling through the contents and it makes it hard to use the application normally.

## Expect

The swipe animation needs are smooth and the application must allow the users to scroll through the survey items without any issues.

## Step to reproduce

https://user-images.githubusercontent.com/70877098/175498801-7c44c500-3018-464c-b9e7-305d4db82f19.mov

**Comment by nkhanh44** [comment]
The root cause is my "creation" in a couple of last minutes before the final submission 😭 for putting some fade in/out animation that causes blocking some gesture when scrolling. I removed all of them 👍 .
I also fixed it in this below PR, please check it, anh :muscle:.
ref: https://github.com/nkhanh44/Survey_Nimble/pull/21
